### ISSUE TITLE
Problem with docker_dokuwiki recovery data

### ISSUE THREAD

**Issue by pokapow** [mprasil/movier#1]
I have a problem with your dokuwiki image: https://hub.docker.com/r/mprasil/dokuwiki/

I deleted by error the container, but I still have the volumes with data inside. How can I link a new image with this volumes ? When I build a new one, and remplace manualy the _data folder into new volumes built, I got this error: 
" DokuWiki Setup Error

The datadir ('pages') at /pages is not found, isn't accessible or writable. You should check your config and permission settings. Or maybe you want to run the installer? "
But the permissions are ok.
Can you help me ?

**Comment by mprasil** [comment]
Not related to movier.

**Comment by pokapow** [comment]
I know but a don't have another way to contact you ... Can't help me ?
pokapow@protonmail.com
